### ISSUE TITLE
Feature req: Auto-open like svg preview like Auto-Open Markdown Preview plugin does ?

### ISSUE THREAD

**Issue by mmc41** [kisstkondoros/svgpreview#1]
Could the SVG previewer plugin be extended to automatically open a preview whenever a new SVG file is opened. Just like this plugin does for markdown files [Auto-Open Markdown Preview plugin](https://marketplace.visualstudio.com/items?itemName=hnw.vscode-auto-open-markdown-preview)?

**Comment by kisstkondoros** [comment]
I've tried the extension and I find it annoying, I think it was implemented before the editor tabs was added to vscode, now it randomly opens and closes documents....
It does so by executing the command "workbench.action.closeEditorsInOtherGroups". As it's name tells you it closes all the other editors to have a free group (left, center or right pane).

I've tried another approach: keeping only one svg preview active at once, showing the last selected svg. Unfortunatelly this can't be done also ,since VSCode does not list such editor instances in vscode.window.visibleTextEditors there is no way currently to keep exactly one document opened.
(I have the feeling that I could hack around this somehow, which I'm going to try later).

Until that, could you please explain the goal behind the suggestion? A user story would be nice in the following form:

> As  a < type of user >, I want to < function >, so that < goal >

**Comment by kisstkondoros** [comment]
Please check v0.1.1, it introduces a new flag which can be set in the workspace's settings.json like so

```
"svgpreview.singletonmode": true
```

This will change the behaviour of the SVG preview to always show the last opened svg file as content.

**Comment by kisstkondoros** [comment]
I'll close this until further feedback

**Comment by mmc41** [comment]
I tried the new version with "svgpreview.singletonmode": true.
It worked once fine. When I selected files it updated the preview automatically. But after I closed the windows, it does not work anymore - even after a restart. Somehow the preview window is not the active tab.

My goal: As a developer of a web project with lots of svg files with confusing names I want to be able to quickly identify file which svg files contains which graphics inside VS (without selecting preview on each an every file). Just like I can do with png files.
