### ISSUE TITLE
Adding zoom functionality

### ISSUE THREAD

**Issue by chaosloki** [kisstkondoros/svgpreview#3]
While working on bigger svg files, it would be helpfull to be able to zoom in.
Smaller one maybe be able to zoom in.

**Comment by kisstkondoros** [comment]
Sorry for taking that much to react to this, actually I was thinking about a possible solution for this for some time now ^^.
The problem is that I could only achieve this by enclosing the svg in some html + js wrapper and feed it with vscode by executing the vscode.previewHTML function, but I read a ticket about that vscode developers are not liking this approach and I think they are going to do something with this (improving the api). Also it would be really though to keep e.g. zoom level & position on subsequent updates, which could also be solved by ... executing an own http server open a custom html page from it in vscode with the command vscode.previewHTML and communicate with this instance via websockets. 👎 

I see the need for it, but it would most likely make the extension unstable.
I hope you understand.
